"""report_renderer.py — Assemble a Markdown audit report from AuditReport + Scores.

Pure, deterministic. Does not import anthropic, playwright, or any I/O module.
render() always returns a str and never raises.
"""

from __future__ import annotations

from ui_analyzer.xml_parser import AuditReport, Tier1Finding, Tier2Finding, Tier3Finding, Tier4Finding
from ui_analyzer.scorer import Scores, stars_to_display


def render(
    report: AuditReport,
    scores: Scores,
    app_type: str,
    image_source: str,
    axe_succeeded: bool,
    model: str = "claude-sonnet-4-6",
) -> str:
    """Assemble the final Markdown report string. Always returns str, never raises."""
    lines: list[str] = []

    # --- Header ---
    tier1_mode_display = (
        "Authoritative (axe-core)"
        if axe_succeeded
        else "Estimated (visual)"
    )

    lines.append("# UI Analysis Report")
    lines.append("")
    lines.append(f"**App type:** {app_type}")
    lines.append(f"**Input:** {image_source}")
    lines.append(f"**Tier 1 mode:** {tier1_mode_display}")
    lines.append(f"**Model:** {model}")
    lines.append("")
    lines.append("---")
    lines.append("")

    # --- Overall Score table ---
    overall_stars = stars_to_display(scores.overall)
    lines.append(f"## Overall Score: {overall_stars} ({scores.overall} / 5)")
    lines.append("")
    lines.append("| Tier | Score | Weight |")
    lines.append("|------|-------|--------|")
    lines.append(f"| Tier 1 — Accessibility | {stars_to_display(scores.tier1)} | 40% |")
    lines.append(f"| Tier 2 — Visual Structure | {stars_to_display(scores.tier2)} | 35% |")
    lines.append(f"| Tier 3 — Usability | {stars_to_display(scores.tier3)} | 25% |")
    lines.append(f"| Tier 4 — Domain Patterns | {scores.tier4_flag_count} flags | — |")
    lines.append("")
    lines.append("---")
    lines.append("")

    # --- Tier 1 ---
    lines.append("## Tier 1 — Accessibility (WCAG 2.1 AA)")
    lines.append("")
    if report.inventory:
        lines.append(report.inventory)
        lines.append("")
    lines.append("**Findings:**")
    lines.append("")
    if report.tier1_findings:
        for f in report.tier1_findings:
            lines.append(_render_tier1_finding(f))
            lines.append("")
    else:
        lines.append("*No issues found.*")
        lines.append("")
    lines.append("---")
    lines.append("")

    # --- Tier 2 ---
    lines.append("## Tier 2 — Visual Structure (Gestalt / CRAP)")
    lines.append("")
    if report.structure_observation:
        lines.append(report.structure_observation)
        lines.append("")
    lines.append("**Findings:**")
    lines.append("")
    if report.tier2_findings:
        for f in report.tier2_findings:
            lines.append(_render_tier23_finding(f))
            lines.append("")
    else:
        lines.append("*No issues found.*")
        lines.append("")
    lines.append("---")
    lines.append("")

    # --- Tier 3 ---
    lines.append("## Tier 3 — Usability & Affordance")
    lines.append("")
    lines.append("**Findings:**")
    lines.append("")
    if report.tier3_findings:
        for f in report.tier3_findings:
            lines.append(_render_tier23_finding(f))
            lines.append("")
    else:
        lines.append("*No issues found.*")
        lines.append("")
    lines.append("---")
    lines.append("")

    # --- Tier 4 ---
    lines.append(f"## Tier 4 — Domain Patterns ({app_type})")
    lines.append("")
    if report.tier4_findings:
        for f in report.tier4_findings:
            lines.append(_render_tier4_finding(f))
            lines.append("")
    else:
        lines.append("*No issues found.*")
        lines.append("")
    lines.append("---")
    lines.append("")

    # --- parse_warnings passthrough ---
    if report.parse_warnings:
        lines.append("---")
        lines.append("")
        warnings_text = "; ".join(report.parse_warnings)
        lines.append(f"⚠️ Parse warning: {warnings_text}")
        lines.append("")

    # --- Footer ---
    lines.append(f"*Generated by ui-analyzer v1 using {model}*")

    return "\n".join(lines)


def _render_tier1_finding(f: Tier1Finding) -> str:
    icon = "❌" if f.result == "FAIL" else "✅"
    estimated_label = " *(ESTIMATED — verify manually)*" if f.estimated else ""
    lines = [
        f"{icon} **{f.result}** — WCAG {f.criterion}",
        f"Element: `{f.element}`{estimated_label}",
        f"Issue: {f.observed} (required {f.required})",
        f"Recommendation: {f.recommendation}",
    ]
    return "\n".join(lines)


def _render_tier23_finding(f: Tier2Finding | Tier3Finding) -> str:
    severity_icon = "🔴" if f.severity == 3 else "⚠️"
    lines = [
        f"{severity_icon} **Severity {f.severity}** — {f.principle}",
        f"Element: {f.element}",
        f"Issue: {f.issue}",
        f"Recommendation: {f.recommendation}",
    ]
    if f.nielsen_tag is not None:
        lines.append(f"Nielsen heuristic: #{f.nielsen_tag}")
    return "\n".join(lines)


def _render_tier4_finding(f: Tier4Finding) -> str:
    lines = [
        f"🚩 **Flag** — {f.pattern}",
        f"Element: {f.element}",
        f"Issue: {f.issue}",
        f"Recommendation: {f.recommendation}",
    ]
    return "\n".join(lines)
